import { useTheme } from '../context/ThemeContext'
import LegalPage from './LegalPage'

function Disclaimer() {
  const { darkMode } = useTheme()
  const p = `mb-4 leading-relaxed`
  const h = `text-xl font-semibold mt-8 mb-3 ${darkMode ? 'text-white' : 'text-gray-900'}`

  return (
    <LegalPage title="Disclaimer">
      <p className={p}>Last updated: August 2026</p>

      <div className={`p-4 rounded-xl mb-6 border ${darkMode ? 'bg-amber-900/20 border-amber-700/30 text-amber-200' : 'bg-amber-50 border-amber-200 text-amber-800'}`}>
        <p className="font-semibold mb-1">Medical Disclaimer</p>
        <p className="text-sm">
          DermaAI provides AI-assisted preliminary information for educational purposes only. It is NOT a medical diagnosis tool and should NEVER be used as a substitute for professional medical advice, diagnosis, or treatment.
        </p>
      </div>

      <h2 className={h}>No Medical Diagnosis</h2>
      <p className={p}>
        The information provided by DermaAI, including any skin analysis results, risk assessments, or health guidance, is generated by artificial intelligence and is intended for informational and educational purposes only. It does not constitute medical advice, diagnosis, or treatment recommendation.
      </p>

      <h2 className={h}>Always Consult a Professional</h2>
      <p className={p}>
        Always seek the advice of a qualified dermatologist or other licensed healthcare provider with any questions you may have regarding a skin condition or medical concern. Never disregard professional medical advice or delay in seeking it because of information you have received from DermaAI.
      </p>

      <h2 className={h}>AI Limitations</h2>
      <p className={p}>
        Our AI models, while trained on diverse medical datasets, have inherent limitations. They may not account for all individual variations, comorbidities, or edge cases. AI-generated assessments may contain inaccuracies and should always be validated by a qualified healthcare professional.
      </p>

      <h2 className={h}>No Doctor-Patient Relationship</h2>
      <p className={p}>
        Use of DermaAI does not establish a doctor-patient relationship between you and DermaAI or its operators. The platform is a tool to supplement — not replace — professional medical evaluation.
      </p>

      <h2 className={h}>Emergency Situations</h2>
      <p className={p}>
        If you believe you have a medical emergency, call your local emergency services immediately. DermaAI is not designed to handle emergency situations and should not be relied upon in such cases.
      </p>

      <h2 className={h}>Accuracy of Information</h2>
      <p className={p}>
        While we strive to provide accurate and up-to-date information, we make no representations or warranties about the completeness, accuracy, reliability, or suitability of the information provided by DermaAI.
      </p>
    </LegalPage>
  )
}

export default Disclaimer
